image: python

stages:
  - build
  - deploy

check:
  stage: build
  before_script:
    - pip3 install black numpy
  script:
    - black . --check
    - python3 -m unittest discover -s finam -v

documentation:
  stage: build
  before_script:
    - pip3 install sphinx numpy
  script:
    - export PYTHONPATH="."
    - sphinx-apidoc --separate -o docs finam
    - sphinx-build -W -b html docs docs/build
    - mv docs/build public/
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script: "true"
  artifacts:
    paths:
      - public
  only:
    - main
