image: python

stages:
  - build
  - deploy

check:
  stage: build
  before_script:
    - pip3 install black numpy pandas
  script:
    - black --check --diff --color .
    - pip3 install --editable .[test]
    - python -m pytest --cov finam --cov-report term-missing -v tests/

documentation:
  stage: build
  before_script:
    - pip3 install sphinx numpy
  script:
    - pip3 install --editable .
    - sphinx-apidoc --separate -o docs src/finam
    - sphinx-build -W -b html docs docs/build
    - mv docs/build public/
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script: "true"
  artifacts:
    paths:
      - public
  only:
    - main
