image: python

stages:
  - build
  - deploy

check:
  stage: build
  before_script:
    - pip3 install black numpy pandas
  script:
    - black . --check
    - pip3 install --editable .
    - python3 -m unittest discover -s tests -v

documentation:
  stage: build
  before_script:
    - pip3 install sphinx numpy
  script:
    - pip3 install --editable .
    - sphinx-apidoc --separate -o docs src/finam
    - sphinx-build -W -b html docs docs/build
    - mv docs/build public/
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script: "true"
  artifacts:
    paths:
      - public
  only:
    - main
